name: Ubuntu CppCheck

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CppCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Run CppCheck    
      shell: bash
      working-directory: ${{github.workspace}}/lib      
      run: cppcheck --error-exitcode=1 --std=c++17 .
