name: Ubuntu CMake Clang

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment     
      run: cmake -E make_directory ${{github.workspace}}/build-clang

    - name: Configure CMake    
      shell: bash
      working-directory: ${{github.workspace}}/build-clang      
      run: cmake $GITHUB_WORKSPACE .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/ClangToolchain.cmake

    - name: Build
      working-directory: ${{github.workspace}}/build-clang
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Run
      working-directory: ${{github.workspace}}/build-clang
      shell: bash
      run: ./SampleLibApp

    - name: Test
      working-directory: ${{github.workspace}}/build-clang
      shell: bash
      run: ctest -C $BUILD_TYPE
